dist: trusty
sudo: required
language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - doxygen

before_script:
  - git log -2

after_success:
  - cd ..
  - cd doxygen
  - doxygen Doxyfile
  - chmod +x gh-pages.sh
  - ./gh-pages.sh

script:
  - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-8
  - export CXX=/usr/bin/g++-8
  - gcc -v && g++ -v && cmake --version
  - goback=$(pwd)
  - mkdir vk
  - cd vk
  - travis_retry curl -L https://sdk.lunarg.com/sdk/download/1.1.108.0/linux/vulkansdk-linux-x86_64-1.1.108.0.tar.gz | tar xz
  - cd 1.1.108.0
  - source ./setup-env.sh
  - cd $goback 
  - mkdir sdl
  - cd sdl
  - travis_retry curl -L https://www.libsdl.org/release/SDL2-2.0.10.tar.gz | tar xz
  - cd SDL2-2.0.10
  - ./configure                  > /dev/null 2>&1
  - make                         > /dev/null 2>&1
  - sudo make install            > /dev/null 2>&1
  - cd $goback
  - mkdir sdl_image
  - cd sdl_image
  - travis_retry curl -L https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.3.tar.gz | tar xz
  - cd SDL2_image-2.0.3
  - ./configure                  > /dev/null 2>&1
  - make                         > /dev/null 2>&1
  - sudo make install            > /dev/null 2>&1
  - cd $goback
  - cd examples/general/
  - cmake .
  - make 
